version: "3.8"

services:
    db:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - "3306:3306"

    backend:
        build: .
        ports:
            - "3000:3000"
        environment:
            DATABASE_URL: ${DATABASE_URL}
        depends_on:
            - db
        volumes:
            - .:/app
        command: sh -c "npx prisma migrate dev && npm run dev"
